### ISSUE TITLE
Strict option when validating against schema

### ISSUE THREAD

**Issue by martinhAllied** [corenova/yang-js#110]
Would be good to have option to validate strictly. 
This would mean 
* No fields added
* No object values turned into arrays of one item, when an array was expected

**Comment by martinhAllied** [comment]
Great. Thank you so much.  In our case it's been difficult to manage the unexpected fixes to the data.  So cleanly rejecting everything would be of benefit.

**Comment by sekur** [comment]
Staged for 0.24 release

**Comment by martinhAllied** [comment]
Great!   Thanks!
