### ISSUE TITLE
Yang.compose() results in container undefined as root container for every input.

### ISSUE THREAD

**Issue by eduardnegru** [corenova/yang-js#114]
For every value of config there is always a root container called "undefined" generated.

```
            const model = Yang.compose(config);
            const yangModel = model.toString(); 
```

Is this the desired behaviour? If yes, what is the purpose of having an undefined container every time?

**Comment by saintkepha** [comment]
Unfortunately Yang.compose is currently *broken*.   I’ll get around to restoring the functionality on it soon.

**Comment by saintkepha** [comment]
As to the schema returning `container undefined` as the root, this is because the config JS object is not named and we need to describe that the config object as a container element.  I believe there is an optional argument that we can specify into .compose in order to name the container.

**Comment by saintkepha** [comment]
The below will allow you to specify a name for the container. 

`Yang.compose(config, { tag: “my-config” })`
