### ISSUE TITLE
[Question] Working with Multiple Schemas

### ISSUE THREAD

**Issue by tomasol** [corenova/yang-js#117]
How do I create a `YangInstance` from two or more yang schemas? [Documentation](https://github.com/corenova/yang-js/blob/HEAD/TUTORIAL.md#working-with-yang-schema) shows an example where only one main schema is used.

**Comment by sekur** [comment]
Have you checked here?
https://github.com/corenova/yang-js/blob/HEAD/TUTORIAL.md#working-with-multiple-schemas
