### ISSUE TITLE
toObject() returning TypeError

### ISSUE THREAD

**Issue by herrlax** [corenova/yang-js#15]
The toObject()-function is returning an error:
`[TypeError: Object.keys called on non-object]`
when trying to convert a yang model into json.

I've tried a minimal model and found this converts correctly into a json-object:
`module my-module {
	prefix "mymodule";
}` 

While this produces the error:
`module my-module {
	prefix "mymodule";
	container foo {
		description "bar";	
	}
}`

This bug does not seem to exist in v.0.14.10, but is present in v.0.14.18.

**Comment by saintkepha** [comment]
Thanks @herrlax for flagging this bug, I'll capture the fix in an upcoming 0.14.19 package later today.
