### ISSUE TITLE
TypeError: Can't add property _eventsCount, object is not extensible

### ISSUE THREAD

**Issue by ramukima** [corenova/yang-js#21]
I was trying to run yang-cord project and saw this error when starting the server -

events.js:221
target._eventsCount = 0;
^
TypeError: Can't add property _eventsCount, object is not extensible
at _addListener (events.js:221:25)
at Model.addListener (events.js:270:10)
at EventEmitter. (*....../yang-cord/lib/api/server.js:14:17)

I patched it like below to make it work locally -
https://github.com/corenova/yang-js/blob/master/src/yang.coffee#L29

```
      '_events':   writable: true
      '_eventsCount':   writable: true
```

**Comment by saintkepha** [comment]
Thanks @ramukima your change looks great.  Can you create a PR?  I think I'm on a much older version of node.js which did not require this property.  I recently introduced Object.preventExtensions to the Model so it may potentially break other emitter behavior if there are other private properties that it dynamically creates based on different function calls.  Thanks for your help!

**Comment by ramukima** [comment]
I do not have permission to push to a branch on this repository.

**Comment by saintkepha** [comment]
I've sent you an invite with write permissions to this repo.  Thanks!

**Comment by ramukima** [comment]
Got it, pushed and created a PR. Please merge.

**Comment by ramukima** [comment]
Thanks, works.
