### ISSUE TITLE
yang-js unique referring to descendant nodes is not supported?

### ISSUE THREAD

**Issue by sindhukothe** [corenova/yang-js#57]
a unique clause that reference to not the immediate children of the container/group, but to a descendant further down does not seem to work.
Following yang: https://github.com/openconfig/public/blob/master/release/models/network-instance/openconfig-network-instance.yang
It throws an error:
ExpressionError: [module(openconfig-network-instance)/grouping(network-instance-top)/container(network-instances)/list(network-instance)/container(interfaces)/list(interface)/unique(config/interface,config/subinterface)] referenced unique items do not have leaf elements

**Comment by saintkepha** [comment]
fixed in develop branch
