### ISSUE TITLE
When a module tries to augment same node, error is thrown

### ISSUE THREAD

**Issue by sindhukothe** [corenova/yang-js#61]
Seems like it is a standard practice in yangs (e.g. open-config yang:
https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-if-ip.yang)
to augment the same node multiple times.
The spec did not mention anything in this regard.
But the parser throws the following error:
ExpressionError: [module(openconfig-if-ip)] constraint violation for 'augment /oc-if:interfaces/oc-if:interface/oc-if:subinterfaces/oc-if:subinterface' - already defined

**Comment by saintkepha** [comment]
Hmm... interesting. 

OK, we can allow duplicate arg values if the element is not a configuration node statement such as container, leaf, etc...

**Comment by saintkepha** [comment]
fixed in develop

**Comment by saintkepha** [comment]
closing, please re-open if issue persists.
