### ISSUE TITLE
require-instance of type instance-identifier

### ISSUE THREAD

**Issue by vcshox** [corenova/yang-js#65]
In the following example:
schema:
```yang
module schema {
  prefix "schema";
  container c {
    leaf l1 {
      type string;
    }
  }

  leaf l2 {
    type instance-identifier;
}
```
data:
```JSON
{
  "schema:c":{
    "l1":"ABC"
  },
  "schema:l2":"/schema:c/l1"
}
```
yang-js works fine when I eval the data. 

Nevertheless, when I add sub-statement `require-instance` (no matter `true` or `false`) and eval, yang-js always throws an error. 

Is there a bug or maybe I misunderstood the [RFC](https://tools.ietf.org/html/rfc6020#section-9.13.2)?

**Comment by saintkepha** [comment]
Hi @vcshox - I'll take a closer look next week, it's been a busy week. :-)

**Comment by vcshox** [comment]
@saintkepha Thank you!!
