### ISSUE TITLE
wrong regexp generated in string pattern (typedef)

### ISSUE THREAD

**Issue by AdCsoft** [corenova/yang-js#67]
The regexp generated for any pattern is not "pattern" but must be: "^pattern$" otherwise any expression incuding a valid expression will match, for example if the pattern in a typedef is "[A].*[B]" QQQQQABQQQQ would match.
:-)
ciao
Andrea

**Comment by saintkepha** [comment]
Thanks, you’re right. I’ll update code to force a complete string match.
