### ISSUE TITLE
Support for concatenating quoted strings

### ISSUE THREAD

**Issue by demonicblue** [corenova/yang-js#7]
The parser seems to ignore concatenation of quoted strings. For example, "hel" + "lo" should be equivalent to "hello". This behavior is noticed when parsing patterns containing regular patterns. 
An example is 
**typedef domain-name**
in [ietf-inet-types.yang](https://github.com/mbj4668/pyang/blob/master/modules/ietf/ietf-inet-types.yang).

The parses seems to only parse the first substring as a regular expression which will fail as it is not valid on its own.

Note: ietf-inet-types.yang will not parse anyway beacause of #6

**Comment by saintkepha** [comment]
@demonicblue I've checked for this issue and found that this was already working as expected.  I've introduced additional test cases in *test/extensions/type.coffee* under the *string* section to explicitly check for string concat parsing behavior.
