### ISSUE TITLE
leafref does not support 'require-instance' statement

### ISSUE THREAD

**Issue by quantang** [corenova/yang-js#70]
Hi,

I found that yang-js cannot handle the {'require-instance': false} in leafref type, which should not throw an error even if it fails to find a matching instance based on the path.

I can try to propose a fix later if you don't mind. :P

**Comment by saintkepha** [comment]
Hey @quantang - there was a prior issue #65 which was addressed with a commit recently. It's in the master branch but I haven't published a new version of yang-js that captures the fix yet. See if you can reproduce it with a latest git pull of yang-js.

**Comment by quantang** [comment]
Hi @saintkepha - I saw your change on #65 which was addressing the 'require-instance' on 'instance-identifier', instead of the 'leafref' type. So they are different and I can repro it in the master branch.

Cheers.

**Comment by saintkepha** [comment]
Ah, you're right. Sorry I should've read your original post more carefully. Yes, I'd like to see your proposed fix, I think something similar to #65 should serve this case.

**Comment by quantang** [comment]
Yes, I take your code as an example, as I am new to CoffeeScript.
Any feedback is welcome.

**Comment by saintkepha** [comment]
Thanks for adding a test case alongside the fix. That really helps!

**Comment by quantang** [comment]
It is my pleasure. :)
