### ISSUE TITLE
Shall we return Yang Property[] in List.change?

### ISSUE THREAD

**Issue by quantang** [corenova/yang-js#98]
Hi @saintkepha,

I know that you added the List.change property to return the newly created list items. Right now, it returns the pure JS objects. I am thinking whether it would be more useful if we return them as a Property list, which could give us more information than the pure JS object, such as the List item key. 

Cheers.

**Comment by saintkepha** [comment]
Recent change to use Proxy objects now returns an array of Proxy objects for List.change which provides abstraction to access other useful information. Also, List.changes now directly return ListItem properties.
